name: release
on:
  push:
    branches:
      - master
    paths:
      - iget-python
    tags:
      - "v*.*.*"
jobs:
  build-zipapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -m zipapp --output iget.pyz iget-python
      - uses: softprops/action-gh-release@v1
        with:
          files: iget.pyz
